### ISSUE TITLE
Create an Autocomplete Component to Select Courses

### ISSUE THREAD

**Issue by kerfootj** [VikeLabs/scheduler-front-end#23]
# User Story
As a user, I want to be able to select courses from a dropdown.

# Description
Create an [autocomplete](https://material-ui.com/components/autocomplete/) component that gets courses that users can choose from. The options will filter as the user types.

# Additional Details 
See: https://material-ui.com/components/autocomplete/#asynchronous-requests
Course data can be obtained from: https://uvic-scheduler-server.herokuapp.com/courses
Course data can be filtered by adding query params to the above url: ?term=201901&search=CSC
Use the Autocomplete onChange prop to get the selection
After selecting a course from the dropdown the input should clear

Component Props
* onAddCourse(course: String) - a function that takes the course added as the only param 

# Acceptance Criteria
- [ ] Any course must be selectable
- [ ] When a course is selected it is returned by calling the onAddCourse() prop with the selected course
- [ ] After selecting a course the input is automatically cleared
- [ ] Tests are created for the component and they all pass

**Comment by nicolepeverley** [comment]
Only needs to check the course list for the given semester.
