### ISSUE TITLE
Add input validation to sign up form

### ISSUE THREAD

**Issue by kerfootj** [VikeLabs/scheduler-front-end#41]
# User Story
As a developer, I want to make sure user input is correct

# Description
Add input validation to the sign up form.

# Additional Details 
Use "yup"
https://www.npmjs.com/package/yup

* Ensure that the email provided is an email
* Password contains lower and uppercase letters and is at least 6 characters long
* Provided feedback when field is incorrect
* Disable the sign up button until all fields are filled and pass validation

# Acceptance Criteria
- [ ] Inputs are validated
- [ ] Feedback is given on invalid fields
- [ ] Tests are written and pass

**Comment by Atsu-Imo** [comment]
Hi, I tried to add input validation to sign up form in #43.
But I can't write tests.
I'm glad if it helps a little
