### ISSUE TITLE
Find a Weekly Calendar

### ISSUE THREAD

**Issue by nicolepeverley** [VikeLabs/scheduler-front-end#7]
# User Story
As a \<user\>, I want to see a weekly calendar.

# Description
Find a weekly calendar option to use within the app.

# Additional Details 

# Acceptance Criteria
- Weekly calendar option is chosen for the project.

**Comment by nicolepeverley** [comment]
We can possibly look into some of these:

https://ourcodeworld.com/articles/read/55/top-5-best-jquery-scheduler-and-events-calendar-for-web-applications

**Comment by nicolepeverley** [comment]
Looks like schedule courses probably used "jQuery week calendar" which isn't maintained anymore

**Comment by nicolepeverley** [comment]
Sarah and I like this one and it works with react and typescript :)

https://github.com/fullcalendar/fullcalendar-react

**Comment by nicolepeverley** [comment]
Started implementing full calendar in #18

**Comment by kerfootj** [comment]
Implemented in pr#21
